---
title: "Case Study C - HIV"
author: "Oumaima Al Qoh, Francisco Arrieta, Lucia Camenisch, Manuela Giansante, Emily Schmidt, Camille Beatrice Valera"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    toc: true # creating a table of contents (toc)
    toc_float: 
      collapsed: false # toc does not collapse and is shown as a sidebar (toc_float)
    number_sections: true # document sections are numbered
    theme: cosmo
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, fig.align = "center")
```

```{r packages}
library(data.table)
library(missForest)
library(caret)       # confusion matrix
# library(ggplot2)
# library(e1071)

# library(MASS)
# library(gridExtra)
# library(fabletools)
# library(forecast)
```

```{r}
aids <- fread("Caids.csv")
aids[, sex := as.factor(sex)]
aids[, type := factor(type, levels = c("DP", "CP"), ordered = TRUE)]
```


```{r}
set.seed(256)
aids_completed <- missForest(aids, variablewise = TRUE)
aids <- aids_completed$ximp
```

```{r}
aids[, sex := as.numeric(sex) - 1]
aids[, type := as.numeric(type) - 1]
```

```{r}
# Partitioning into training (60%) and validation (40%) 
set.seed(1)
train.index <- sample(c(1:dim(aids)[1]), dim(aids)[1]*0.6)
test.index <- setdiff(c(1:dim(aids)[1]), train.index)  

# Collect all the columns with training rows into training set 
train <- aids[train.index, ]
test <- aids[test.index, ]
```


```{r}
model <- glm(formula =  type ~ ., data = train, family = 'binomial')
summary(model)
```


```{r}
# Predict CD4, CD8, and RNA counts for testing set
type_pred <- predict(model, newdata = test, type = 'response')
type_pred <- round(type_pred)
```

```{r}
confusionMatrix(data = as.factor(type_pred), reference = as.factor(test$type), positive = "1")
```




